### PR TITLE
Add new blue accent colors

### PR DESCRIPTION
**Pull request by ramnach**
… for showing frozen memberships

### CODE REVIEW

**Comment by ramnach** [comment]
To Show frozen memberships in the mobile app - Design Team @Will Sloan came up with a requirement of Blue color, when I checked Apollo foundation it was not added but later @fernandogelin added all the base values 

So have added blue lm and dm values in semanticPalette file. Checked with @Will Sloan on what strategy we should follow for the naming and he insisted to keep it as blue - so left it as blue 

I dont want to add this in accentPalette as there was only one value defined for each color ( but we need lm and dm value ) 

I could have added it in primaryPalette file too but decided to go with  semanticPalette

We should have some definitions on where color should be added ( and based on what) when we have two similar files ( if not in the long run there will be an issue ) 

@fernandogelin let me know if you have any questions. If not kindly request you to approve and merge it.

**Review by fernandogelin — COMMENTED** [review]
@ramnach thanks for adding that!! And very good point about adding some documentation around where colors should be added.  In this case I don't think `blue` is a semantic color, it doesn't have any semantic meaning.  More generally, when will that blue be used? Is there a specific case or semantic meaning for blue? 

I think in this case, if blue doesn't have a semantic meaning, it can be added to the accentPallete. It's okay to have dm/lm in that file. In fact, I think the other accent colors need both dm/lm.

One small request, could you update the PR title to be more meaningful of the work being done, for example: "Add new blue accent colors". No need to explain why or when it will be used.  And if there's a JIRA ticket, do you mind linking it here?

**Comment by ramnach** [comment]
Thank you @fernandogelin - I agree - may be the commit message was automatically taken as the Title - but as you requested I have changed it :) 

As per design team - they want to use this to show Frozen membership status in the mobile app 

I agree - it should be added to accentPalette and will do update it :) 

Will link Jira ticket if we have one :)

**Comment by ramnach** [comment]
@fernandogelin have updated the PR and added blue color in accentPalette :) 

Kindly review it

**Review by fernandogelin — APPROVED** [review]
LGTM!! Thanks @ramnach

**Pull request merged**
